#!/usr/bin/env python3
"""gen-showreel.py -- generate m5/showreel.cfg (SEPTEMBER S1).

    python3 test/gen-showreel.py

The reel is 67 `defer` lines on an absolute timeline. Hand-editing it means
recomputing every subsequent timestamp, so it is GENERATED: change a hold here
and every downstream time follows. The generated file is what ships and is
tracked; this is how it was derived.

DEMO DURATIONS ARE MEASURED, NOT GUESSED (2026-09-01). The first cut budgeted
act 3 at 36 s for a demo that turns out to be 16 s long, and the Chthon arena sat
empty for twenty seconds. Method: play each demo with `echo TICK_n` defers every
2 s and find the last tick before the engine's own CL_Disconnect -- taking care
that `playdemo` ITSELF issues a disconnect first, which is what made the first
parse read every demo as ending instantly.

    demo11  e3m1        ~72 s      demo7   e1m7        16 s
    demo8   start.bsp    32 s      demo12  e1m1        >78 s

Act budgets are sized against those with margin. demo7 is short enough that act 3
plays it TWICE rather than dropping a toggle.
"""
import io, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, 'm5', 'showreel_ab.cfg')

# Measured demo durations, seconds. Sizing the acts against these is the whole
# reason this script exists.
DEMO = {'demo11': 72, 'demo7': 16, 'demo8': 32, 'demo12': 78}

FULL = ("r_viewfbo 2; r_hdr_shoulder 0.75; r_redglow 1.5; r_lightningbeam_m5 1; "
        "r_lavaboil 0.6; r_lavaflow 1; r_lavashimmer 4; r_volumetric 1; "
        "r_volumetric_ground 2.5; r_volumetric_water 1; r_volumetric_lavaglow 0.5; "
        "r_wateralpha_force 1; r_wateralpha 0.7; r_volumetric_liquidfade 0.5; "
        "rt_metal 1; rt_metal_walllight 0.8; rt_metal_fog 1; rt_metal_gi 1; "
        "rt_metal_liquids 0.45; r_viewscale 0.667; r_metalfx 2; r_edr 1")

# NOT the shipped defaults -- several of these default ON, so "stock Quake" has
# to be spelled out rather than assumed.
STOCK = ("r_viewfbo 0; r_hdr_shoulder 0; r_redglow 0; r_lightningbeam_m5 0; "
         "r_lavaboil 0; r_lavaflow 0; r_lavashimmer 0; r_volumetric 0; "
         "r_volumetric_ground 0; r_volumetric_liquidfade 0; r_wateralpha_force 0; "
         "rt_metal 0; rt_metal_walllight 0; rt_metal_fog 0; rt_metal_gi 0; "
         "rt_metal_liquids 0; r_metalfx 0; r_viewscale 1; r_edr 0")

HEADER = """// showreel.cfg -- SEPTEMBER S1. The whole fork, A-Z, in one realtime run.
//
//   exec showreel.cfg          ~4 minutes, five acts, no input needed
//
// GENERATED by test/gen-showreel.py -- edit that, not this. The timeline is
// absolute, so changing one hold by hand means recomputing 67 timestamps.
//
// ACT 1 ramps stock Quake -> the full look, so you see it ACCUMULATE.
// ACTS 2-5 then take each feature AWAY and put it back against the same scene a
// second later. That is the only way to judge what any ONE thing contributes; a
// monotonic ramp cannot show you that. Each act runs the demo that actually
// demonstrates its features.
//
// NO ENGINE CODE. `defer <seconds> "<cmd>"` is realtime and `cprint` is
// SCR_Centerprint_f. Verified 2026-09-01: defers queued before a playdemo survive
// that demo's map load, and an explicit playdemo sets demonum = -1
// (cl_demo.c:427) so a finished demo does NOT auto-advance -- it sits idle until
// the next scheduled playdemo. That is what makes chained acts safe.
//
// EVERY PLAYDEMO IS FOLLOWED BY `togglemenu 0`. With cl_startdemos 0 the engine
// goes straight to the MAIN MENU at boot (that is the cvar's documented
// behaviour) and playdemo does not dismiss it, so the reel plays underneath the
// menu. It is closed again one second later too, in case the map load reopens it.
//
// EVERY ACT LOADS ITS DEMO BEFORE IT LABELS ITSELF, and that ordering is load-
// bearing rather than tidy: `cprint` TRAPS THE ENGINE (exit 133) when fullscreen
// with no map loaded. Measured 2026-09-01; it is a stock DarkPlaces command and
// the crash is not this fork's. Windowed is fine and fullscreen-with-a-map is
// fine, so a windowed test will never catch it.
//
// RUN IT ON METAL -- the SDF bolt, lava shimmer, MetalFX and EDR all
// magenta-sentinel on GL, so five of these toggles would show nothing.
//
// DEMO DURATIONS, MEASURED (see gen-showreel.py for the method):
//     demo11 e3m1 ~72 s   demo7 e1m7 16 s   demo8 start 32 s   demo12 e1m1 >78 s
// demo7 is short enough that act 3 plays it TWICE rather than dropping a toggle.
//
// WHICH STAGES MOVE, measured on a frozen e1m3 camera. A first attempt compared
// frames 5 s apart DURING PLAYBACK and read 98% on everything -- that is the
// demo's own motion, and it would have passed a completely broken reel:
//     murk 97.9  fogkernel 97.5  metalfx 85.9  walllight 54.1  gi 53.9
//     groundfog 42.9  edr 27.9  rt 10.9  liquid 5.9  hdr 2.0
//     shoulder 0.7  redglow 0.3  bolt 0.2  lava 0.2
// The last four are dead air ON THAT BED -- the shoulder needs a bright scene,
// red glow needs red texels, nothing fires the bolt on a frozen camera, and e1m3
// has no lava. None is a bug, and it is why acts 3-5 run elsewhere.

scr_centertime 4
cl_startdemos 0
"""

L = []
t = [0.0]
def at(d, c):
    t[0] += d
    L.append('defer %g "%s"\n' % (round(t[0], 1), c))
def say(lab, cmd, hold):
    at(hold, 'cprint \\"%s\\"; echo REEL: %s; %s' % (lab, lab.split('\\n')[0], cmd))
def ab(lab, off, on, hold):
    say("%s\\nOFF" % lab, off, hold)
    say("%s\\nON"  % lab, on,  hold)
def act(title, sub, demo, setup):
    # PLAYDEMO FIRST, THEN THE LABEL. `cprint` TRAPS THE ENGINE (exit 133) when
    # fullscreen with no map loaded -- measured 2026-09-01, and it is a stock
    # DarkPlaces command, not something this fork added. Windowed is fine, and
    # fullscreen WITH a map loaded is fine. Labelling before the demo exists is
    # therefore a crash, and it is how the first cut of this reel was written.
    L.append("\n// ---- %s (%s, %s s) %s\n" % (title, demo, DEMO[demo], '-' * 18))
    at(4, 'playdemo %s; togglemenu 0; %s' % (demo, setup))
    at(1, 'togglemenu 0; cprint \\"%s\\n%s\\"; echo REEL: %s' % (title, sub, title.split(' --')[0].lower().replace(' ', '')))

L.append(HEADER)

L.append("\n// ======================== ACT 1 -- THE RAMP ==============================\n")
L.append(STOCK + "\n")
at(2, 'playdemo demo11; togglemenu 0')
at(1, 'togglemenu 0; cprint \\"ACT 1 -- THE RAMP\\nstock Quake, then one thing at a time\\"; echo REEL: act1')
for lab, cmd in [
 ("1. INTERNAL HDR\\nthe scene renders into a float buffer", "r_viewfbo 2"),
 ("2. HIGHLIGHT SHOULDER\\nhot pixels roll off instead of clipping", "r_hdr_shoulder 0.75"),
 ("3. RED GLOW\\nsaturated reds emit -- bands, health boxes, flame", "r_redglow 1.5"),
 ("4. THE THUNDERBOLT\\njagged, forked, and it lights the room", "r_lightningbeam_m5 1"),
 ("5. LIVING LAVA\\nthe crust boils, flows, bends the air above it",
  "r_lavaboil 0.6; r_lavaflow 1; r_lavashimmer 4; r_volumetric_lavaglow 0.5"),
 ("6. VOLUMETRIC MURK\\nfog with real depth, settled on the floor", "r_volumetric 1"),
 ("7. GROUND FOG\\na dry-ice layer that billows and drifts", "r_volumetric_ground 2.5"),
 ("8. LIQUID MURK\\nwater goes clear, and fogs with distance",
  "r_wateralpha_force 1; r_wateralpha 0.7; r_volumetric_water 1; r_volumetric_liquidfade 0.5"),
 ("9. RAY-TRACED SHADOWS\\nsoft shadows from every light", "rt_metal 1; rt_metal_liquids 0.45"),
 ("10. FULL WALL LIGHTING\\nthe baked lightmap is gone entirely", "rt_metal_walllight 0.8"),
 ("11. RAY-TRACED FOG\\nlit per march step -- god rays, torch warmth", "rt_metal_fog 1"),
 ("12. BOUNCE LIGHTING\\none diffuse bounce -- rooms bleed colour", "rt_metal_gi 1"),
 ("13. TEMPORAL UPSCALING\\nrenders at 2/3 and reconstructs", "r_viewscale 0.667; r_metalfx 2"),
 ("14. HDR OUTPUT\\ngenuinely above-white pixels", "r_edr 1")]:
    say(lab, cmd, 5)

act("ACT 2 -- WHAT EACH ONE DOES", "full stack; watch things vanish and return", 'demo11', FULL)
at(3, 'echo REEL: act2 begin')
for lab, off, on in [
 ("VOLUMETRIC MURK",    "r_volumetric 0",       "r_volumetric 1"),
 ("RAY-TRACED SHADOWS", "rt_metal 0",           "rt_metal 1"),
 ("FULL WALL LIGHTING", "rt_metal_walllight 0", "rt_metal_walllight 0.8"),
 ("RAY-TRACED FOG",     "rt_metal_fog 0",       "rt_metal_fog 1"),
 ("BOUNCE LIGHTING",    "rt_metal_gi 0",        "rt_metal_gi 1"),
 ("TEMPORAL UPSCALING", "r_metalfx 0",          "r_metalfx 2")]:
    ab(lab, off, on, 4)

# demo7 is 16 s. Two pairs at 2.5 s plus a 1 s lead is 11 s -- five seconds of
# margin. The first cut used 3 s holds and a 2 s lead and overran the demo.
act("ACT 3 -- LAVA", "the Chthon arena, where e3m1 has none", 'demo7', FULL)
at(1, 'echo REEL: act3 begin')
ab("LAVA BOIL",    "r_lavaboil 0",    "r_lavaboil 0.6", 2.5)
ab("HEAT SHIMMER", "r_lavashimmer 0", "r_lavashimmer 4", 2.5)
at(2, 'echo REEL: act3 replay; playdemo demo7; togglemenu 0')
at(1, 'echo REEL: act3 second half')
ab("LAVA FLOW",        "r_lavaflow 0",             "r_lavaflow 1", 2.5)
ab("LAVA GLOW IN AIR", "r_volumetric_lavaglow 0",  "r_volumetric_lavaglow 0.5", 2.5)

act("ACT 4 -- THE THUNDERBOLT", "start.bsp, lightning-heavy", 'demo8', FULL)
at(2, 'echo REEL: act4 begin')
for lab, off, on in [
 ("M5 BOLT\\nvs the stock straight quad", "r_lightningbeam_m5 0",         "r_lightningbeam_m5 1"),
 ("BOLT LIGHTS THE ROOM",                 "r_lightningbeam_m5_light 0",   "r_lightningbeam_m5_light 1"),
 ("BOLT SCATTERS IN FOG",                 "r_lightningbeam_m5_fog 0",     "r_lightningbeam_m5_fog 2.6"),
 ("FRAYED TIPS",                          "r_lightningbeam_m5_frizzle 0", "r_lightningbeam_m5_frizzle 1")]:
    ab(lab, off, on, 3)

act("ACT 5 -- LIQUIDS", "e1m1 slime, seen from the bank", 'demo12', FULL)
at(3, 'echo REEL: act5 begin')
for lab, off, on in [
 ("CLEAR WATER\\nforced transparent on stock vis", "r_wateralpha_force 0",      "r_wateralpha_force 1"),
 ("MURK INSIDE LIQUID",                            "r_volumetric_water 0",      "r_volumetric_water 1"),
 ("LIQUID FADES INTO FOG",                         "r_volumetric_liquidfade 0", "r_volumetric_liquidfade 0.5"),
 ("RT LIGHT ON LIQUID",                            "rt_metal_liquids 0",        "rt_metal_liquids 0.45")]:
    ab(lab, off, on, 4)

at(5, 'cprint \\"THAT IS THE LOT\\n\\"; echo REEL: done')

io.open(OUT, 'w').write(''.join(L))
print('wrote %s -- %.0f s (%.1f min), %d defers'
      % (os.path.relpath(OUT, ROOT), t[0], t[0] / 60.0,
         sum(1 for x in L if x.startswith('defer'))))
