#!/usr/bin/env python3
"""gen-showreel.py -- generate m5/showreel.cfg and m5/showreel_check.cfg (SEPTEMBER2 F).

    python3 test/gen-showreel.py

THEMED PLAYTHROUGHS (Seb, 2026-09-07): each demo plays for its theme and the
features are ADDED one at a time, ~25-30 s each, in the fork's own order, so a
feature is always on screen in a scene that shows it. Labels are TOP-LEFT (the
console notify area, sized by con_notifysize, left-aligned) and the fps meter is
BOTTOM-RIGHT -- nothing centred, because a centred label hides the thing it
describes. The finale is two TIMEDEMOs (Stock, then Best) with the engine's own
result line left on screen. Sound is ON and the room reverb gets its section.

NO ENGINE CODE: `defer` is realtime, `echo` writes the notify area, `playdemo`
and `timedemo` are stock. The verified rules from the first reel stand:
a demo must be loaded before anything is printed to the screen (cprint traps
fullscreen with no map; echo is safe but the order is kept), `playdemo` sets
demonum -1 so a finished demo sits idle until the next scheduled one, and every
playdemo is followed by `togglemenu 0`.

DEMO DURATIONS are parsed from each .dem's own svc_time stamps (2026-09-07; the
four measured on 2026-09-01 agree within a few seconds). Sections are sized
with margin so a label never outlives its demo.

The reel runs ON TOP OF the player's config: it only touches what it toggles,
restores the notify area at the end and re-execs config.cfg so nothing it set
survives the run (most of these cvars are archived).

showreel_check.cfg is the SAME timeline plus a screenshot 8 s into every
section and a quit at the end -- the headless self-check (test/README.md).
"""
import io, os, re, sys, importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, 'm5', 'showreel.cfg')
OUTC = os.path.join(ROOT, 'm5', 'showreel_check.cfg')

# durations parsed from the .dem files (2026-09-07), seconds
DEMO = {'demo11': 79, 'demo7': 15, 'demo8': 33, 'demo12': 131, 'demo15': 57,
        'demo22': 74, 'demo26': 44, 'demo34': 27, 'demo29': 55, 'demo35': 79, 'demo36': 48,
        'demo24': 68, 'demo25': 69, 'demo28': 62}
# packet counts (~frames) for the timedemo finale's holds
FRAMES = {'demo26': 3377, 'demo24': 4976, 'demo28': 4750, 'demo25': 4797}
# where the water is: demo35 (e1m2) from frame 650 = 8.3 s, demo36 (e4m1) from frame 450 = 6.0 s
# (Seb, 2026-09-07: the e1m1 demo "is featuring the lights and is more of a diagnostic")

# the tier tables straight from menu.c (the only authority)
spec = importlib.util.spec_from_file_location('ct', os.path.join(ROOT, 'test', 'perf', 'check-tiers.py'))
ct = importlib.util.module_from_spec(spec); spec.loader.exec_module(ct)
TABLE = ct.parse_menu()
src = open(os.path.join(ROOT, 'menu.c'), encoding='utf-8', errors='replace').read()
i = src.index('m5_quality_levers[] ='); body = src[i:src.index('\n};', i)]
ORDER = [m.group(1) for m in re.finditer(r'\{\s*&(\w+)\s*,\s*\{([^}]*)\}\s*\}', body) if m.group(1) in TABLE]
def fmt(v): return str(int(round(v))) if abs(v - round(v)) < 1e-9 else ('%.4f' % v).rstrip('0').rstrip('.')
def tier(name): return '; '.join('%s %s' % (k, fmt(TABLE[k][ct.T[name]])) for k in ORDER)

# "stock Quake" spelled out: several of these default ON
STOCK = ("m5_stock 1; cl_particles_quake 1; r_lerpmodels 0; r_viewfbo 0; r_hdr_shoulder 0; "
         "r_redglow 0; r_lightningbeam_m5 0; r_lavaboil 0; r_lavaflow 0; r_lavashimmer 0; "
         "r_volumetric 0; r_volumetric_ground 0; r_volumetric_liquidfade 0; r_wateralpha_force 0; "
         "rt_metal 0; rt_metal_walllight 0; rt_metal_fog 0; rt_metal_gi 0; rt_metal_liquids 0; "
         "r_metalfx 0; r_viewscale 1; r_edr 0; m5_dust 0; cl_particles_lighting 0; "
         "snd_reverb 0; snd_occlusion_lowpass 0; m5_torch 0")
FULL  = ("m5_stock 0; cl_particles_quake 0; r_lerpmodels 1; r_viewfbo 2; r_hdr_shoulder 0.75; "
         "r_redglow 0.5; r_lightningbeam_m5 1; r_lavaboil 0.5; r_lavaflow 1; r_lavashimmer 3; "
         "r_volumetric 1; r_volumetric_ground 3; r_volumetric_water 1; r_volumetric_lavaglow 0.5; "
         "r_wateralpha_force 1; r_wateralpha 0.7; r_volumetric_liquidfade 0.5; "
         "rt_metal 1; rt_metal_walllight 0.8; rt_metal_fog 1; rt_metal_gi 1; rt_metal_liquids 0.45; "
         "rt_metal_lightsample 1; rt_metal_fog_froxel 1; r_volumetric_liquidfloor 1; "
         "r_viewscale 0.667; r_metalfx 2; r_edr 1; m5_dust 512; cl_particles_lighting 2; "
         "snd_reverb 1; snd_occlusion_lowpass 1; m5_torch 0")

HEADER = '''// showreel.cfg -- SEPTEMBER2 F. The fork in themed playthroughs, labelled top-left.
//
//   exec showreel.cfg      ~%s, no input needed, sound ON, run it on Metal
//
// GENERATED by test/gen-showreel.py -- edit that, not this (the timeline is absolute).
// Each demo plays for its theme; features are ADDED one at a time, ~25-30 s each,
// in the fork's own order. The finale runs timedemo demo26 at Stock and then at
// Best and leaves the engine's fps line on screen. Ends by re-exec'ing config.cfg.
//
'''

L = []; C = []; t = [0.0]; n = [0]; shots = []
def emit(d, cmd, both=True):
    t[0] += d; line = 'defer %g "%s"\n' % (round(t[0], 1), cmd); L.append(line); C.append(line)
def label(title, desc, cmd):
    n[0] += 1
    emit(0, 'reellabel \\"^7%d  %s\\" \\"^3%s\\"; echo REEL: %s; %s' % (n[0], title, desc, title, cmd))
    C.append('defer %g "screenshot reel_%02d.tga"\n' % (round(t[0] + 8, 1), n[0])); shots.append(title)
def section(title, demo, setup, hold_before=0):
    L.append('\n// ---- %s (%s, %s s) %s\n' % (title, demo, DEMO[demo], '-' * 16)); C.append(L[-1])
    emit(hold_before, 'playdemo %s; togglemenu 0; %s' % (demo, setup))
    emit(2.5, 'togglemenu 0; echo REEL: section %s' % title)
    return t[0]

# the notify area is OFF for the body of the reel (the demos' own pickup messages
# would otherwise share the corner with the captions); the finale turns it back on
# for the engine's timedemo result line
SETUP = ('con_notify 0; developer 0; m5_reellabel_size 14; m5_reellabel_time 9; m5_reellabel_corner 0; '
         'showfps 1; scr_centertime 0; cl_startdemos 0; con_chatsound 0')

# HIS GAMMA IS CALIBRATED FOR WALL LIGHTING (r_brightness 0.1 against a shipped 0.5), and
# anything that turns the ray tracer off at those values is a black screen (the
# 2026-09-05 Stock record). So the reel runs NEUTRAL gamma until FULL WALL LIGHTING and
# restores his values there; the closing exec config.cfg restores them regardless.
NEUTRAL = 'r_brightness 0.5; r_hdr_scenebrightness 1; v_gamma 1; v_contrast 1'
def his_gamma():
    cfg = os.path.expanduser('~/Library/Application Support/darkplaces/m5/config.cfg')
    vals = {'r_brightness': '0.5', 'r_hdr_scenebrightness': '1', 'v_gamma': '1', 'v_contrast': '1'}
    if os.path.exists(cfg):
        for line in open(cfg, encoding='utf-8', errors='replace'):
            m = re.match(r'"?(\w+)"?\s+"([^"]*)"', line.strip())
            if m and m.group(1) in vals: vals[m.group(1)] = m.group(2)
    return '; '.join('%s %s' % kv for kv in vals.items())
HIS = his_gamma()
L.append(SETUP + '\n'); C.append(SETUP + '\n')

# ---- 1. e3m1: the picture, built up from 1996 -------------------------
section('THE PICTURE, FROM 1996 UP', 'demo11', STOCK, 2)
label('STOCK QUAKE', 'GLQuake 1.09: the 1996 picture on the same map', '')
emit(24, 'echo REEL: hold')
label('THE MODERN BASELINE', 'float scene, highlight shoulder, bloom, smooth animation', 'm5_stock 0; cl_particles_quake 0; r_lerpmodels 1; r_viewfbo 2; r_hdr_shoulder 0.75; ' + NEUTRAL)
emit(24, 'echo REEL: hold')
label('RED GLOW', 'saturated reds emit: bands, health boxes, flame', 'r_redglow 0.5')
section('THE MURK', 'demo11', '', 24)
label('VOLUMETRIC MURK', 'fog with real depth, settled on each room\'s floor', 'r_volumetric 1')
emit(24, 'echo REEL: hold')
label('GROUND FOG', 'a dry-ice layer that billows and drifts', 'r_volumetric_ground 3')
emit(24, 'echo REEL: hold')
label('DUST AND LIT PARTICLES', 'motes in the air; smoke and blood take the room\'s light', 'm5_dust 512; cl_particles_lighting 2')
section('RAY TRACING', 'demo11', '', 24)
label('RAY-TRACED SHADOWS', 'soft shadows from every light, over the baked lightmap', 'rt_metal 1')
emit(24, 'echo REEL: hold')
label('FULL WALL LIGHTING', 'the baked lightmap is gone: every wall lit by the ray tracer', 'rt_metal_walllight 0.8; ' + HIS)
emit(24, 'echo REEL: hold')
label('RAY-TRACED FOG', 'the fog lit per step: god rays, torch warmth, shadows in the air', 'rt_metal_fog 1; rt_metal_lightsample 0; rt_metal_fog_froxel 0')
section('BOUNCE, UPSCALE, HDR', 'demo11', '', 24)
label('BOUNCE LIGHTING', 'one diffuse bounce: rooms bleed their own colour', 'rt_metal_gi 1')
emit(24, 'echo REEL: hold')
label('TEMPORAL UPSCALING', 'renders at two thirds and reconstructs the rest', 'r_viewscale 0.667; r_metalfx 2')
emit(24, 'echo REEL: hold')
label('HDR OUTPUT', 'genuinely above-white pixels on an HDR display', 'r_edr 1')

# ---- 2. e1m2 hall: fog in motion --------------------------------------
section('FOG IN MOTION', 'demo22', FULL + '; rt_metal_lightsample 0; rt_metal_fog_froxel 0', 24)
label('EVERY LIGHT SHADOWS THE FOG', 'the fog light pick: torches cast shadows in the air', 'rt_metal_lightsample 1')
emit(24, 'echo REEL: hold')
label('THE 3D FOG VOLUME', 'the fog kept in depth slices: calm walking, no smear', 'rt_metal_fog_froxel 1')
emit(24, 'echo REEL: hold')
label('THE HANDLAMP', 'a torch with a cone, a bulb and a flicker', 'm5_torch 1')

# ---- 3. e1m7: lava, twice ----------------------------------------------
section('LIVING LAVA', 'demo7', FULL + '; r_lavaboil 0; r_lavaflow 0; r_lavashimmer 0; r_volumetric_lavaglow 0; m5_torch 0', 24)
label('THE CRUST BOILS AND FLOWS', 'the lava texture churns and creeps', 'r_lavaboil 0.5; r_lavaflow 1')
section('LIVING LAVA, AGAIN', 'demo7', '', 11)
label('HEAT SHIMMER AND GLOW', 'the air above it bends; the fog warms near it', 'r_lavashimmer 3; r_volumetric_lavaglow 0.5')

# ---- 4. start: the bolt and the ball ------------------------------------
section('THE THUNDERBOLT', 'demo8', FULL + '; r_lightningbeam_m5 0', 11)
label('THE STOCK BOLT', 'the 1996 straight beam', '')
emit(12, 'echo REEL: hold')
label('THE M5 THUNDERBOLT', 'jagged, forked, frayed; it lights the room and scatters in the fog', 'r_lightningbeam_m5 1')
section('BALL LIGHTNING', 'demo34', FULL, 16)
label('BALL LIGHTNING', 'the ninth weapon: a plasma sphere that arcs at what it passes', '')

# ---- 5. e1m2 and e4m1: liquids (the water-heavy demos, from the frames Seb named) -------
section('WATER', 'demo35', FULL + '; r_wateralpha_force 0; r_volumetric_water 0; r_volumetric_liquidfade 0; rt_metal_liquids 0', 24)
emit(8.3 - 2.5, 'echo REEL: demo35 reaches frame 650')
label('OPAQUE WATER', 'stock Quake water: a painted sheet', '')
emit(23, 'echo REEL: hold')
label('CLEAR WATER', 'forced transparent on the stock maps', 'r_wateralpha_force 1')
emit(23, 'echo REEL: hold')
label('MURK INSIDE THE WATER', 'the fog thickens and tints under the surface', 'r_volumetric_water 1')
section('WATER, IN THE ELDER WORLD', 'demo36', '', 22)
emit(6.0 - 2.5, 'echo REEL: demo36 reaches frame 450')
label('WATER FADES INTO THE FOG', 'the surface recedes into the murk with distance', 'r_volumetric_liquidfade 0.5')
emit(21, 'echo REEL: hold')
label('RAY-TRACED LIGHT ON WATER', 'the surface takes the room\'s light', 'rt_metal_liquids 0.45')

# ---- 6. e1m4: the lake --------------------------------------------------
section('THE LAKE', 'demo15', FULL + '; r_volumetric_watermist 0; r_volumetric_liquidfloor 0', 21)
label('THE BARE LAKE', 'the fog anchored to the lake bed: none over the water', '')
emit(18, 'echo REEL: hold')
label('MIST ON THE WATER', 'a band of mist lying on the surface', 'r_volumetric_watermist 0.69')
emit(18, 'echo REEL: hold')
label('THE LAKE AS THE FOG\'S FLOOR', 'the murk settles on the water as it does on land: no step at the shore', 'r_volumetric_liquidfloor 1')

# ---- 7. e2m4: sound ----------------------------------------------------
section('SOUND: THE ROOM', 'demo26', FULL + '; snd_reverb 0; snd_occlusion_lowpass 0', 18)
label('DRY SOUND', 'every sample as recorded, nothing added', '')
emit(20, 'echo REEL: hold')
label('ROOM REVERB', 'the level\'s own shape becomes a reverb: crypts ring, corridors are tight', 'snd_reverb 1')
section('SOUND: THE WALL', 'demo26', '', 22)
label('OCCLUSION LOW-PASS', 'a monster behind a door is muffled, not merely quieter', 'snd_occlusion_lowpass 1')

# ---- 8. the finale: four action demos, each at Stock then at Best --------
# The engine's own result line is the exhibit: the notify area comes back on with
# a long fade for it, and the menu a finished timedemo opens is closed after each.
# Holds are sized from each demo's frame count at 120 fps (Stock) and ~95 fps (Best)
# plus the load and a few seconds to read the line.
L.append('\n// ---- PERFORMANCE: timedemo x8, Stock then Best on four action demos ----\n'); C.append(L[-1])
emit(30, 'con_notify 3; con_notifytime 60; reellabel; echo REEL: perf begin')
k = 0
for demo in ['demo26', 'demo24', 'demo28', 'demo25']:
    # Stock is sized at 120, not its real ~300: a windowed run is presentation-capped at
    # the display's 120 Hz and a timedemo cut short by the next one prints no result
    for tname, fps in [('Stock', 120.0), ('Best', 95.0)]:
        k += 1
        hold = FRAMES[demo] / fps + 10
        emit(2, 'reellabel \\"^7PERFORMANCE %d of 8: %s at %s\\" \\"^3the engine\'s own fps line follows\\"; echo REEL: perf %s %s; %s; timedemo %s' % (k, demo, tname.upper(), demo, tname, tier(tname), demo))
        emit(hold, 'togglemenu 0; echo REEL: perf %s %s over' % (demo, tname))
        C.append('defer %g "screenshot reel_perf_%d_%s_%s.tga"\n' % (round(t[0] + 2, 1), k, demo, tname))
emit(10, 'reellabel \\"^7THAT IS THE LOT\\" \\"^3your settings are back\\"; echo REEL: done; exec config.cfg')
C.append('defer %g "quit"\n' % round(t[0] + 4, 1))

total = t[0] + 4
head = HEADER % ('%d minutes' % round(total / 60))
io.open(OUT, 'w').write(head + ''.join(L))
io.open(OUTC, 'w').write(head.replace('showreel.cfg --', 'showreel_check.cfg -- the SELF-CHECK twin of') + ''.join(C))
print('wrote m5/showreel.cfg and m5/showreel_check.cfg -- %.0f s (%.1f min), %d labels' % (total, total / 60, n[0]))
