#!/usr/bin/env python3
"""release/make-public-config.py <his config.cfg> <out.cfg>

The PUBLIC build's default settings: Seb's LOOK on the Best tier, with everything that
belongs to one person or one machine taken out. It is derived, never hand-kept, so a look
he re-tunes reaches the next public build by itself.

  kept      every archived cvar that is part of the picture (fog, RT, bloom, the gamma
            chain the look was approved under, the feature masters)
  dropped   binds (id1's default.cfg supplies them, Key_Init adds the fork's), video mode,
            mouse, volumes, names, records, developer chatter
  forced    the Best row of menu.c's m5_quality_levers[] -- read from the table itself,
            so a retier cannot leave this file behind -- vsync on, developer off
"""
import importlib.util, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('ct', os.path.join(HERE, '..', 'test', 'perf', 'check-tiers.py'))
ct = importlib.util.module_from_spec(spec); spec.loader.exec_module(ct)

DROP_EXACT = {
    'm5_horde_best', 'developer', 'sensitivity', 'fov', 'crosshair', 'volume', 'bgmvolume',
    'snd_width', 'con_notify', 'con_notifytime', 'con_chatsound', 'cl_showfps',
    'scr_screenshot_jpeg', 'm5_torch', 'viewsize', 'cl_startdemos',
}
DROP_PREFIX = ('vid_', '_cl_', 'cl_name', 'm_', 'joy', 'in_', 'net_', 'sv_', 'snd_speed',
               'snd_channels', 'scr_conalpha', 'sbar_', 'menu_', 'saved', 'cl_forwardspeed',
               'cl_backspeed', 'cl_sidespeed', 'lookspring', 'lookstrafe', 'freelook')
FORCE = {'vid_vsync': '1', 'scr_screenshot_jpeg': '0', 'scr_screenshot_png': '1'}   # PNG: libpng is bundled, libjpeg is not

def fmt(v):
    return ('%g' % v)

def main():
    src, dst = sys.argv[1], sys.argv[2]
    table = ct.parse_menu()
    best = ct.TIERS.index('Best')
    out, seen = [], set()
    for line in open(src, encoding='utf-8', errors='replace'):
        m = re.match(r'^"([^"]+)"\s+"(.*)"\s*$', line)
        if not m:
            continue                        # binds, unbindall, comments
        name = m.group(1)
        if name in DROP_EXACT or name.startswith(DROP_PREFIX) or name in table or name in FORCE:
            continue
        out.append('"%s" "%s"' % (name, m.group(2)))
        seen.add(name)
    for name, vals in sorted(table.items()):
        out.append('"%s" "%s"' % (name, fmt(vals[best])))
    for name, v in FORCE.items():
        out.append('"%s" "%s"' % (name, v))
    with open(dst, 'w') as f:
        f.write('// MetalQuake: the shipped default settings (the Best tier). Generated by\n'
                '// release/make-public-config.py. Your own settings are saved elsewhere the\n'
                '// first time you quit, and win from then on; this file is never written to.\n')
        f.write('\n'.join(sorted(out)) + '\n')
    print('public config: %d cvars (%d look, %d tier levers) -> %s' % (len(out), len(seen), len(table), dst))

main()
